package Traitement;









import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;

import javax.media.Buffer;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


public class UI_Travail extends javax.swing.JFrame {

    /**
     * Creates new form UI_Travail
     */
    public UI_Travail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_Traitement = new javax.swing.JLabel();
        label_Cam = new javax.swing.JLabel();
        btn_LanceCam = new javax.swing.JButton();
        btn_LanceTraitement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_LanceCam.setText("Cam");
        btn_LanceCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LanceCamActionPerformed(evt);
            }
        });

        btn_LanceTraitement.setText("Traitement");
        btn_LanceTraitement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LanceTraitementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_Traitement, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btn_LanceCam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(btn_LanceTraitement)
                .addGap(194, 194, 194))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(label_Cam, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_Traitement, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LanceCam)
                    .addComponent(btn_LanceTraitement))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(label_Cam, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btn_LanceCamActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	
    	  
			
			afficheCam = new Thread(){
				

				

				public void run(){

					while (true){


						Buffer buff;
						BufferToImage buferToImage;
						Image image1=null;



						FrameGrabbingControl f = (FrameGrabbingControl) player.getControl("javax.media.control.FrameGrabbingControl");
						buff = f.grabFrame();
						buferToImage = new BufferToImage((VideoFormat) buff.getFormat());
						image1=  buferToImage.createImage(buff);
						BufferedImage ImageOriginal = (BufferedImage) image1;

						imagereduite=resizeImage(ImageOriginal);
						//FeedLabel.setIcon(new ImageIcon (imagereduite) );
						//    			    	
						
						if(imagereduite!=null){
							
							
							
						}
					}
				}
		

		};  afficheCam.start();
    }
    

    private void btn_LanceTraitementActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	afficheTraitement = new Thread(){
			

			

			public void run(){

				while (true){


					
					//    			    	
					
					if(imagereduite!=null){
						
						DetecteBalonBleu d= new DetecteBalonBleu();
						Balon = d.DetecteV(imagereduite);
						Erosion S= new Erosion();
						BufferedImage Erosion =  S.erosion(Balon);
						Dilatation E=  new Dilatation();
						BufferedImage Dilataion = E.dilatation(Erosion);
						Median5 M =  new Median5();
					 median = M.DetectV(Dilataion);
					 int car[]= new int[4];
						FindSquare care = new FindSquare();
						car=care.Line(median);
						drawSquare(imagereduite,car);
						label_Cam.setIcon(new ImageIcon(imagereduite));
						label_Traitement.setIcon(new ImageIcon(median));
						
						
						
					}
				}
			}
	

	};  afficheTraitement.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Travail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Travail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Travail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Travail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Travail().setVisible(true);
                Affiche n = new Affiche();
    			player = n.afficheCam();
    			
    			//
    			
    			player.start();
            }
        });
    }
    
    
    public BufferedImage drawSquare(BufferedImage imagein,int []car){
    	Graphics2D G = imagein.createGraphics();

		G.setColor(Color.red);
//		po[0]= iMin ;
//		po[1]=jMin;
//		po[2]=iMax;
//		po[3]=jMax;
		
		G.drawLine(car[0],car[1],car[0],car[3]);
		G.drawLine(car[0],car[1],car[2],car[1]);
		G.drawLine(car[2],car[1],car[2],car[3]);
		G.drawLine(car[0],car[3],car[2],car[3]);
		
		return imagein;
    }
    
    
    public static BufferedImage resizeImageValeur(BufferedImage originalImage,int w, int h){
  		int type=originalImage.getType();
  		BufferedImage ImageReduite = new BufferedImage(w, h, type);
  		Graphics2D g = ImageReduite.createGraphics();
  		g.drawImage(originalImage, 0, 0, w, h, null);
  		g.dispose();

  		return ImageReduite;
  	}
      public static BufferedImage resizeImage(BufferedImage originalImage){
  		int type=originalImage.getType();
  		BufferedImage ImageReduite = new BufferedImage(W, H, type);
  		Graphics2D g = ImageReduite.createGraphics();
  		g.drawImage(originalImage, 0, 0, W, H, null);
  		g.dispose();

  		return ImageReduite;
  	}
      
      private static final int W= 300;
   	private static final int H = 240;
    private BufferedImage imagereduite;
  private  BufferedImage Balon,median;
    private Thread afficheCam,afficheTraitement;
    
    static Player player;
    // Variables declaration - do not modify
    private javax.swing.JButton btn_LanceCam;
    private javax.swing.JButton btn_LanceTraitement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Cam;
    private javax.swing.JLabel label_Traitement;
    // End of variables declaration
}
